/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ActivateTicketRequest {
  
  @SerializedName("ticketId")
  private String ticketId = null;
  @SerializedName("userId")
  private String userId = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getTicketId() {
    return ticketId;
  }
  public void setTicketId(String ticketId) {
    this.ticketId = ticketId;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivateTicketRequest activateTicketRequest = (ActivateTicketRequest) o;
    return (this.ticketId == null ? activateTicketRequest.ticketId == null : this.ticketId.equals(activateTicketRequest.ticketId)) &&
        (this.userId == null ? activateTicketRequest.userId == null : this.userId.equals(activateTicketRequest.userId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.ticketId == null ? 0: this.ticketId.hashCode());
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivateTicketRequest {\n");
    
    sb.append("  ticketId: ").append(ticketId).append("\n");
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
