/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import com.openmove.aroundsardinia.TicketsstatusSelector;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Body1 {
  
  @SerializedName("selector")
  private TicketsstatusSelector selector = null;
  @SerializedName("sort")
  private Object sort = null;
  @SerializedName("limit")
  private Integer limit = null;
  @SerializedName("skip")
  private Integer skip = null;
  @SerializedName("options")
  private Object options = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public TicketsstatusSelector getSelector() {
    return selector;
  }
  public void setSelector(TicketsstatusSelector selector) {
    this.selector = selector;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getSort() {
    return sort;
  }
  public void setSort(Object sort) {
    this.sort = sort;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getLimit() {
    return limit;
  }
  public void setLimit(Integer limit) {
    this.limit = limit;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getSkip() {
    return skip;
  }
  public void setSkip(Integer skip) {
    this.skip = skip;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getOptions() {
    return options;
  }
  public void setOptions(Object options) {
    this.options = options;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body1 body1 = (Body1) o;
    return (this.selector == null ? body1.selector == null : this.selector.equals(body1.selector)) &&
        (this.sort == null ? body1.sort == null : this.sort.equals(body1.sort)) &&
        (this.limit == null ? body1.limit == null : this.limit.equals(body1.limit)) &&
        (this.skip == null ? body1.skip == null : this.skip.equals(body1.skip)) &&
        (this.options == null ? body1.options == null : this.options.equals(body1.options));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.selector == null ? 0: this.selector.hashCode());
    result = 31 * result + (this.sort == null ? 0: this.sort.hashCode());
    result = 31 * result + (this.limit == null ? 0: this.limit.hashCode());
    result = 31 * result + (this.skip == null ? 0: this.skip.hashCode());
    result = 31 * result + (this.options == null ? 0: this.options.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body1 {\n");
    
    sb.append("  selector: ").append(selector).append("\n");
    sb.append("  sort: ").append(sort).append("\n");
    sb.append("  limit: ").append(limit).append("\n");
    sb.append("  skip: ").append(skip).append("\n");
    sb.append("  options: ").append(options).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
