/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import com.openmove.aroundsardinia.IdmregisterCompany;
import com.openmove.aroundsardinia.IdmregisterSupport;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Body7 {
  
  @SerializedName("name")
  private String name = null;
  @SerializedName("company")
  private IdmregisterCompany company = null;
  @SerializedName("support")
  private IdmregisterSupport support = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public IdmregisterCompany getCompany() {
    return company;
  }
  public void setCompany(IdmregisterCompany company) {
    this.company = company;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public IdmregisterSupport getSupport() {
    return support;
  }
  public void setSupport(IdmregisterSupport support) {
    this.support = support;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body7 body7 = (Body7) o;
    return (this.name == null ? body7.name == null : this.name.equals(body7.name)) &&
        (this.company == null ? body7.company == null : this.company.equals(body7.company)) &&
        (this.support == null ? body7.support == null : this.support.equals(body7.support));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.company == null ? 0: this.company.hashCode());
    result = 31 * result + (this.support == null ? 0: this.support.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body7 {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("  company: ").append(company).append("\n");
    sb.append("  support: ").append(support).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
