/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import com.openmove.aroundsardinia.TicketsstatusSelector;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Body2 {
  
  @SerializedName("selector")
  private TicketsstatusSelector selector = null;
  @SerializedName("options")
  private Object options = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public TicketsstatusSelector getSelector() {
    return selector;
  }
  public void setSelector(TicketsstatusSelector selector) {
    this.selector = selector;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Object getOptions() {
    return options;
  }
  public void setOptions(Object options) {
    this.options = options;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body2 body2 = (Body2) o;
    return (this.selector == null ? body2.selector == null : this.selector.equals(body2.selector)) &&
        (this.options == null ? body2.options == null : this.options.equals(body2.options));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.selector == null ? 0: this.selector.hashCode());
    result = 31 * result + (this.options == null ? 0: this.options.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body2 {\n");
    
    sb.append("  selector: ").append(selector).append("\n");
    sb.append("  options: ").append(options).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
