/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Body5 {
  
  @SerializedName("stops")
  private List<String> stops = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getStops() {
    return stops;
  }
  public void setStops(List<String> stops) {
    this.stops = stops;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body5 body5 = (Body5) o;
    return (this.stops == null ? body5.stops == null : this.stops.equals(body5.stops));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.stops == null ? 0: this.stops.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body5 {\n");
    
    sb.append("  stops: ").append(stops).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
