/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import com.openmove.aroundsardinia.BurnTicketRequestBurnObj;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class BurnTicketRequest {
  
  @SerializedName("burnObj")
  private BurnTicketRequestBurnObj burnObj = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public BurnTicketRequestBurnObj getBurnObj() {
    return burnObj;
  }
  public void setBurnObj(BurnTicketRequestBurnObj burnObj) {
    this.burnObj = burnObj;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BurnTicketRequest burnTicketRequest = (BurnTicketRequest) o;
    return (this.burnObj == null ? burnTicketRequest.burnObj == null : this.burnObj.equals(burnTicketRequest.burnObj));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.burnObj == null ? 0: this.burnObj.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BurnTicketRequest {\n");
    
    sb.append("  burnObj: ").append(burnObj).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
