/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import com.openmove.aroundsardinia.BurnTicketRequestBurnObjCheck;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class BurnTicketRequestBurnObj {
  
  @SerializedName("code")
  private String code = null;
  @SerializedName("check")
  private BurnTicketRequestBurnObjCheck check = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getCode() {
    return code;
  }
  public void setCode(String code) {
    this.code = code;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public BurnTicketRequestBurnObjCheck getCheck() {
    return check;
  }
  public void setCheck(BurnTicketRequestBurnObjCheck check) {
    this.check = check;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BurnTicketRequestBurnObj burnTicketRequestBurnObj = (BurnTicketRequestBurnObj) o;
    return (this.code == null ? burnTicketRequestBurnObj.code == null : this.code.equals(burnTicketRequestBurnObj.code)) &&
        (this.check == null ? burnTicketRequestBurnObj.check == null : this.check.equals(burnTicketRequestBurnObj.check));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.code == null ? 0: this.code.hashCode());
    result = 31 * result + (this.check == null ? 0: this.check.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BurnTicketRequestBurnObj {\n");
    
    sb.append("  code: ").append(code).append("\n");
    sb.append("  check: ").append(check).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
