/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import com.openmove.aroundsardinia.Password;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GenerateToken {
  
  @SerializedName("clientId")
  private String clientId = null;
  @SerializedName("secret")
  private Password secret = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getClientId() {
    return clientId;
  }
  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Password getSecret() {
    return secret;
  }
  public void setSecret(Password secret) {
    this.secret = secret;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenerateToken generateToken = (GenerateToken) o;
    return (this.clientId == null ? generateToken.clientId == null : this.clientId.equals(generateToken.clientId)) &&
        (this.secret == null ? generateToken.secret == null : this.secret.equals(generateToken.secret));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.clientId == null ? 0: this.clientId.hashCode());
    result = 31 * result + (this.secret == null ? 0: this.secret.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenerateToken {\n");
    
    sb.append("  clientId: ").append(clientId).append("\n");
    sb.append("  secret: ").append(secret).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
