/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import com.openmove.aroundsardinia.UserTicket;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse200 {
  
  public enum ResultEnum {
     AUTHORIZE_NEED,  APPROVED,  NOT_APPROVED,  CANCELED,
  };
  @SerializedName("result")
  private ResultEnum result = null;
  public enum ServiceTypeEnum {
     intesa, 
  };
  @SerializedName("serviceType")
  private ServiceTypeEnum serviceType = null;
  @SerializedName("paymentURL")
  private String paymentURL = null;
  @SerializedName("paymentId")
  private String paymentId = null;
  @SerializedName("ticket")
  private List<UserTicket> ticket = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public ResultEnum getResult() {
    return result;
  }
  public void setResult(ResultEnum result) {
    this.result = result;
  }

  /**
   * PSP identifier
   **/
  @ApiModelProperty(value = "PSP identifier")
  public ServiceTypeEnum getServiceType() {
    return serviceType;
  }
  public void setServiceType(ServiceTypeEnum serviceType) {
    this.serviceType = serviceType;
  }

  /**
   * payment url to redirect the user, if need.
   **/
  @ApiModelProperty(value = "payment url to redirect the user, if need.")
  public String getPaymentURL() {
    return paymentURL;
  }
  public void setPaymentURL(String paymentURL) {
    this.paymentURL = paymentURL;
  }

  /**
   * psp payment identifier
   **/
  @ApiModelProperty(value = "psp payment identifier")
  public String getPaymentId() {
    return paymentId;
  }
  public void setPaymentId(String paymentId) {
    this.paymentId = paymentId;
  }

  /**
   * tickets purchased
   **/
  @ApiModelProperty(value = "tickets purchased")
  public List<UserTicket> getTicket() {
    return ticket;
  }
  public void setTicket(List<UserTicket> ticket) {
    this.ticket = ticket;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return (this.result == null ? inlineResponse200.result == null : this.result.equals(inlineResponse200.result)) &&
        (this.serviceType == null ? inlineResponse200.serviceType == null : this.serviceType.equals(inlineResponse200.serviceType)) &&
        (this.paymentURL == null ? inlineResponse200.paymentURL == null : this.paymentURL.equals(inlineResponse200.paymentURL)) &&
        (this.paymentId == null ? inlineResponse200.paymentId == null : this.paymentId.equals(inlineResponse200.paymentId)) &&
        (this.ticket == null ? inlineResponse200.ticket == null : this.ticket.equals(inlineResponse200.ticket));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.result == null ? 0: this.result.hashCode());
    result = 31 * result + (this.serviceType == null ? 0: this.serviceType.hashCode());
    result = 31 * result + (this.paymentURL == null ? 0: this.paymentURL.hashCode());
    result = 31 * result + (this.paymentId == null ? 0: this.paymentId.hashCode());
    result = 31 * result + (this.ticket == null ? 0: this.ticket.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("  result: ").append(result).append("\n");
    sb.append("  serviceType: ").append(serviceType).append("\n");
    sb.append("  paymentURL: ").append(paymentURL).append("\n");
    sb.append("  paymentId: ").append(paymentId).append("\n");
    sb.append("  ticket: ").append(ticket).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
