/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class PassRequest {
  
  @SerializedName("provider")
  private String provider = null;
  @SerializedName("userId")
  private String userId = null;
  @SerializedName("otp")
  private String otp = null;
  @SerializedName("email")
  private String email = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getProvider() {
    return provider;
  }
  public void setProvider(String provider) {
    this.provider = provider;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getOtp() {
    return otp;
  }
  public void setOtp(String otp) {
    this.otp = otp;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PassRequest passRequest = (PassRequest) o;
    return (this.provider == null ? passRequest.provider == null : this.provider.equals(passRequest.provider)) &&
        (this.userId == null ? passRequest.userId == null : this.userId.equals(passRequest.userId)) &&
        (this.otp == null ? passRequest.otp == null : this.otp.equals(passRequest.otp)) &&
        (this.email == null ? passRequest.email == null : this.email.equals(passRequest.email));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.provider == null ? 0: this.provider.hashCode());
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    result = 31 * result + (this.otp == null ? 0: this.otp.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PassRequest {\n");
    
    sb.append("  provider: ").append(provider).append("\n");
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  otp: ").append(otp).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
