/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import com.openmove.aroundsardinia.TripsreserveconfirmTickets;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ReserveConfirm1 {
  
  @SerializedName("agencyId")
  private String agencyId = null;
  @SerializedName("tickets")
  private List<TripsreserveconfirmTickets> tickets = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getAgencyId() {
    return agencyId;
  }
  public void setAgencyId(String agencyId) {
    this.agencyId = agencyId;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<TripsreserveconfirmTickets> getTickets() {
    return tickets;
  }
  public void setTickets(List<TripsreserveconfirmTickets> tickets) {
    this.tickets = tickets;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReserveConfirm1 reserveConfirm1 = (ReserveConfirm1) o;
    return (this.agencyId == null ? reserveConfirm1.agencyId == null : this.agencyId.equals(reserveConfirm1.agencyId)) &&
        (this.tickets == null ? reserveConfirm1.tickets == null : this.tickets.equals(reserveConfirm1.tickets));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.agencyId == null ? 0: this.agencyId.hashCode());
    result = 31 * result + (this.tickets == null ? 0: this.tickets.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReserveConfirm1 {\n");
    
    sb.append("  agencyId: ").append(agencyId).append("\n");
    sb.append("  tickets: ").append(tickets).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
