/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class StatusTicketRequest {
  
  @SerializedName("ticketId")
  private String ticketId = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getTicketId() {
    return ticketId;
  }
  public void setTicketId(String ticketId) {
    this.ticketId = ticketId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatusTicketRequest statusTicketRequest = (StatusTicketRequest) o;
    return (this.ticketId == null ? statusTicketRequest.ticketId == null : this.ticketId.equals(statusTicketRequest.ticketId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.ticketId == null ? 0: this.ticketId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatusTicketRequest {\n");
    
    sb.append("  ticketId: ").append(ticketId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
