/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import com.openmove.aroundsardinia.SubscriptionItemNotificationHttp;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SubscriptionItemNotification {
  
  @SerializedName("http")
  private SubscriptionItemNotificationHttp http = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public SubscriptionItemNotificationHttp getHttp() {
    return http;
  }
  public void setHttp(SubscriptionItemNotificationHttp http) {
    this.http = http;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionItemNotification subscriptionItemNotification = (SubscriptionItemNotification) o;
    return (this.http == null ? subscriptionItemNotification.http == null : this.http.equals(subscriptionItemNotification.http));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.http == null ? 0: this.http.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionItemNotification {\n");
    
    sb.append("  http: ").append(http).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
