/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class TicketRequest {
  
  @SerializedName("userId")
  private String userId = null;
  @SerializedName("fareId")
  private String fareId = null;
  @SerializedName("quantity")
  private Integer quantity = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getFareId() {
    return fareId;
  }
  public void setFareId(String fareId) {
    this.fareId = fareId;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getQuantity() {
    return quantity;
  }
  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TicketRequest ticketRequest = (TicketRequest) o;
    return (this.userId == null ? ticketRequest.userId == null : this.userId.equals(ticketRequest.userId)) &&
        (this.fareId == null ? ticketRequest.fareId == null : this.fareId.equals(ticketRequest.fareId)) &&
        (this.quantity == null ? ticketRequest.quantity == null : this.quantity.equals(ticketRequest.quantity));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    result = 31 * result + (this.fareId == null ? 0: this.fareId.hashCode());
    result = 31 * result + (this.quantity == null ? 0: this.quantity.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TicketRequest {\n");
    
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  fareId: ").append(fareId).append("\n");
    sb.append("  quantity: ").append(quantity).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
