/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import com.openmove.aroundsardinia.TripsreserveFrom;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class TripsreserveTrips {
  
  @SerializedName("departureDate")
  private String departureDate = null;
  @SerializedName("from")
  private TripsreserveFrom from = null;
  @SerializedName("to")
  private TripsreserveFrom to = null;
  @SerializedName("tripId")
  private String tripId = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getDepartureDate() {
    return departureDate;
  }
  public void setDepartureDate(String departureDate) {
    this.departureDate = departureDate;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public TripsreserveFrom getFrom() {
    return from;
  }
  public void setFrom(TripsreserveFrom from) {
    this.from = from;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public TripsreserveFrom getTo() {
    return to;
  }
  public void setTo(TripsreserveFrom to) {
    this.to = to;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getTripId() {
    return tripId;
  }
  public void setTripId(String tripId) {
    this.tripId = tripId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TripsreserveTrips tripsreserveTrips = (TripsreserveTrips) o;
    return (this.departureDate == null ? tripsreserveTrips.departureDate == null : this.departureDate.equals(tripsreserveTrips.departureDate)) &&
        (this.from == null ? tripsreserveTrips.from == null : this.from.equals(tripsreserveTrips.from)) &&
        (this.to == null ? tripsreserveTrips.to == null : this.to.equals(tripsreserveTrips.to)) &&
        (this.tripId == null ? tripsreserveTrips.tripId == null : this.tripId.equals(tripsreserveTrips.tripId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.departureDate == null ? 0: this.departureDate.hashCode());
    result = 31 * result + (this.from == null ? 0: this.from.hashCode());
    result = 31 * result + (this.to == null ? 0: this.to.hashCode());
    result = 31 * result + (this.tripId == null ? 0: this.tripId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TripsreserveTrips {\n");
    
    sb.append("  departureDate: ").append(departureDate).append("\n");
    sb.append("  from: ").append(from).append("\n");
    sb.append("  to: ").append(to).append("\n");
    sb.append("  tripId: ").append(tripId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
