/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import com.openmove.aroundsardinia.TripsreserveTrips;
import java.math.BigDecimal;
import java.util.*;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class TripsreserveTickets1 {
  
  @SerializedName("_id")
  private String id = null;
  @SerializedName("quantity")
  private BigDecimal quantity = null;
  @SerializedName("totalPrice")
  private BigDecimal totalPrice = null;
  @SerializedName("trips")
  private List<TripsreserveTrips> trips = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getQuantity() {
    return quantity;
  }
  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public BigDecimal getTotalPrice() {
    return totalPrice;
  }
  public void setTotalPrice(BigDecimal totalPrice) {
    this.totalPrice = totalPrice;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<TripsreserveTrips> getTrips() {
    return trips;
  }
  public void setTrips(List<TripsreserveTrips> trips) {
    this.trips = trips;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TripsreserveTickets1 tripsreserveTickets1 = (TripsreserveTickets1) o;
    return (this.id == null ? tripsreserveTickets1.id == null : this.id.equals(tripsreserveTickets1.id)) &&
        (this.quantity == null ? tripsreserveTickets1.quantity == null : this.quantity.equals(tripsreserveTickets1.quantity)) &&
        (this.totalPrice == null ? tripsreserveTickets1.totalPrice == null : this.totalPrice.equals(tripsreserveTickets1.totalPrice)) &&
        (this.trips == null ? tripsreserveTickets1.trips == null : this.trips.equals(tripsreserveTickets1.trips));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.quantity == null ? 0: this.quantity.hashCode());
    result = 31 * result + (this.totalPrice == null ? 0: this.totalPrice.hashCode());
    result = 31 * result + (this.trips == null ? 0: this.trips.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TripsreserveTickets1 {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  quantity: ").append(quantity).append("\n");
    sb.append("  totalPrice: ").append(totalPrice).append("\n");
    sb.append("  trips: ").append(trips).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
