/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class TripRequestOptionsExtra {
  
  @SerializedName("max_walk")
  private Integer maxWalk = null;
  @SerializedName("arriveBy")
  private Boolean arriveBy = null;
  @SerializedName("wheelchair")
  private Boolean wheelchair = null;
  @SerializedName("locale")
  private String locale = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getMaxWalk() {
    return maxWalk;
  }
  public void setMaxWalk(Integer maxWalk) {
    this.maxWalk = maxWalk;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getArriveBy() {
    return arriveBy;
  }
  public void setArriveBy(Boolean arriveBy) {
    this.arriveBy = arriveBy;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getWheelchair() {
    return wheelchair;
  }
  public void setWheelchair(Boolean wheelchair) {
    this.wheelchair = wheelchair;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLocale() {
    return locale;
  }
  public void setLocale(String locale) {
    this.locale = locale;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TripRequestOptionsExtra tripRequestOptionsExtra = (TripRequestOptionsExtra) o;
    return (this.maxWalk == null ? tripRequestOptionsExtra.maxWalk == null : this.maxWalk.equals(tripRequestOptionsExtra.maxWalk)) &&
        (this.arriveBy == null ? tripRequestOptionsExtra.arriveBy == null : this.arriveBy.equals(tripRequestOptionsExtra.arriveBy)) &&
        (this.wheelchair == null ? tripRequestOptionsExtra.wheelchair == null : this.wheelchair.equals(tripRequestOptionsExtra.wheelchair)) &&
        (this.locale == null ? tripRequestOptionsExtra.locale == null : this.locale.equals(tripRequestOptionsExtra.locale));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.maxWalk == null ? 0: this.maxWalk.hashCode());
    result = 31 * result + (this.arriveBy == null ? 0: this.arriveBy.hashCode());
    result = 31 * result + (this.wheelchair == null ? 0: this.wheelchair.hashCode());
    result = 31 * result + (this.locale == null ? 0: this.locale.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TripRequestOptionsExtra {\n");
    
    sb.append("  maxWalk: ").append(maxWalk).append("\n");
    sb.append("  arriveBy: ").append(arriveBy).append("\n");
    sb.append("  wheelchair: ").append(wheelchair).append("\n");
    sb.append("  locale: ").append(locale).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
