/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * payment informations
 **/
@ApiModel(description = "payment informations")
public class UserTicketPayment {
  
  public enum ServiceTypeEnum {
     intesa, 
  };
  @SerializedName("serviceType")
  private ServiceTypeEnum serviceType = null;
  @SerializedName("outcome")
  private Object outcome = null;
  @SerializedName("execute")
  private Object execute = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public ServiceTypeEnum getServiceType() {
    return serviceType;
  }
  public void setServiceType(ServiceTypeEnum serviceType) {
    this.serviceType = serviceType;
  }

  /**
   * original PSP auth response
   **/
  @ApiModelProperty(value = "original PSP auth response")
  public Object getOutcome() {
    return outcome;
  }
  public void setOutcome(Object outcome) {
    this.outcome = outcome;
  }

  /**
   * original PSP capture response
   **/
  @ApiModelProperty(value = "original PSP capture response")
  public Object getExecute() {
    return execute;
  }
  public void setExecute(Object execute) {
    this.execute = execute;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserTicketPayment userTicketPayment = (UserTicketPayment) o;
    return (this.serviceType == null ? userTicketPayment.serviceType == null : this.serviceType.equals(userTicketPayment.serviceType)) &&
        (this.outcome == null ? userTicketPayment.outcome == null : this.outcome.equals(userTicketPayment.outcome)) &&
        (this.execute == null ? userTicketPayment.execute == null : this.execute.equals(userTicketPayment.execute));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.serviceType == null ? 0: this.serviceType.hashCode());
    result = 31 * result + (this.outcome == null ? 0: this.outcome.hashCode());
    result = 31 * result + (this.execute == null ? 0: this.execute.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserTicketPayment {\n");
    
    sb.append("  serviceType: ").append(serviceType).append("\n");
    sb.append("  outcome: ").append(outcome).append("\n");
    sb.append("  execute: ").append(execute).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
