/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class UserTicketFareAttributesMetaTemplateIt {
  
  @SerializedName("title")
  private String title = null;
  @SerializedName("note")
  private String note = null;
  @SerializedName("tos")
  private String tos = null;
  @SerializedName("validitynote")
  private String validitynote = null;
  @SerializedName("piva")
  private String piva = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNote() {
    return note;
  }
  public void setNote(String note) {
    this.note = note;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTos() {
    return tos;
  }
  public void setTos(String tos) {
    this.tos = tos;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getValiditynote() {
    return validitynote;
  }
  public void setValiditynote(String validitynote) {
    this.validitynote = validitynote;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPiva() {
    return piva;
  }
  public void setPiva(String piva) {
    this.piva = piva;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserTicketFareAttributesMetaTemplateIt userTicketFareAttributesMetaTemplateIt = (UserTicketFareAttributesMetaTemplateIt) o;
    return (this.title == null ? userTicketFareAttributesMetaTemplateIt.title == null : this.title.equals(userTicketFareAttributesMetaTemplateIt.title)) &&
        (this.note == null ? userTicketFareAttributesMetaTemplateIt.note == null : this.note.equals(userTicketFareAttributesMetaTemplateIt.note)) &&
        (this.tos == null ? userTicketFareAttributesMetaTemplateIt.tos == null : this.tos.equals(userTicketFareAttributesMetaTemplateIt.tos)) &&
        (this.validitynote == null ? userTicketFareAttributesMetaTemplateIt.validitynote == null : this.validitynote.equals(userTicketFareAttributesMetaTemplateIt.validitynote)) &&
        (this.piva == null ? userTicketFareAttributesMetaTemplateIt.piva == null : this.piva.equals(userTicketFareAttributesMetaTemplateIt.piva));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.note == null ? 0: this.note.hashCode());
    result = 31 * result + (this.tos == null ? 0: this.tos.hashCode());
    result = 31 * result + (this.validitynote == null ? 0: this.validitynote.hashCode());
    result = 31 * result + (this.piva == null ? 0: this.piva.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserTicketFareAttributesMetaTemplateIt {\n");
    
    sb.append("  title: ").append(title).append("\n");
    sb.append("  note: ").append(note).append("\n");
    sb.append("  tos: ").append(tos).append("\n");
    sb.append("  validitynote: ").append(validitynote).append("\n");
    sb.append("  piva: ").append(piva).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
