/**
 * NUCLEUS API
 * OpenMove public APIs documentation. NUCLEUS API exposes a set of APIs tuned to support efficient and easy integration with any customer and to provide the best experience for users. We would welcome the opportunity to refine the specifications better to match your use case. These APIs have a thin nature in order to answer focused questions with very short response times. Some of these APIs also assume a user context, which will allow rolling various ID’s (such as stopId) between requests.
 *
 * OpenAPI spec version: 4.6.0
 * Contact: support@openmove.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.openmove.aroundsardinia;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ValidatePassRequest {
  
  @SerializedName("passId")
  private String passId = null;
  @SerializedName("userId")
  private String userId = null;
  @SerializedName("code")
  private String code = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getPassId() {
    return passId;
  }
  public void setPassId(String passId) {
    this.passId = passId;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getCode() {
    return code;
  }
  public void setCode(String code) {
    this.code = code;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidatePassRequest validatePassRequest = (ValidatePassRequest) o;
    return (this.passId == null ? validatePassRequest.passId == null : this.passId.equals(validatePassRequest.passId)) &&
        (this.userId == null ? validatePassRequest.userId == null : this.userId.equals(validatePassRequest.userId)) &&
        (this.code == null ? validatePassRequest.code == null : this.code.equals(validatePassRequest.code));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.passId == null ? 0: this.passId.hashCode());
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    result = 31 * result + (this.code == null ? 0: this.code.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidatePassRequest {\n");
    
    sb.append("  passId: ").append(passId).append("\n");
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  code: ").append(code).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
